services:

  traefik:
    image: traefik:v3.1
    container_name: piaca-traefik
    restart: unless-stopped
    command:
      - --log.level=INFO
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=piaca-net
      - --entrypoints.web.address=:80
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - piaca-net


  piaca-frontend:
    build:
      context: ./piaca-frontend
      dockerfile: Dockerfile
    container_name: piaca-frontend
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - piaca-net

  example-module:
    build:
      context: ./example-module
      dockerfile: Dockerfile
    container_name: example-module
    restart: unless-stopped
    networks:
      - piaca-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.example.rule=PathPrefix(`/example`)
      - traefik.http.routers.example.entrypoints=web
      - traefik.http.services.example.loadbalancer.server.port=3005

  piaca-core-auth:
    build:
      context: ./piaca-backend/group-a-core-auth
      dockerfile: Dockerfile
    container_name: piaca-core-auth
    restart: unless-stopped
    networks:
      - piaca-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.core-auth.rule=PathPrefix(`/auth`)
      - traefik.http.routers.core-auth.entrypoints=web
      - traefik.http.services.core-auth.loadbalancer.server.port=3001


  piaca-pet-management:
    build:
      context: ./piaca-backend/group-b-pet-management
      dockerfile: Dockerfile
    container_name: piaca-pet-management
    restart: unless-stopped
    networks:
      - piaca-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.pet-management.rule=PathPrefix(`/animals`)
      - traefik.http.routers.pet-management.entrypoints=web
      - traefik.http.services.pet-management.loadbalancer.server.port=3002


  piaca-adoption-ai:
    build:
      context: ./piaca-backend/group-c-adoption-ai
      dockerfile: Dockerfile
    container_name: piaca-adoption-ai
    restart: unless-stopped
    networks:
      - piaca-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.adoption-ai.rule=PathPrefix(`/adoption`)
      - traefik.http.routers.adoption-ai.entrypoints=web
      - traefik.http.services.adoption-ai.loadbalancer.server.port=3003


  piaca-godparenthood:
    build:
      context: ./piaca-backend/group-d-godparenthood
      dockerfile: Dockerfile
    container_name: piaca-godparenthood
    restart: unless-stopped
    networks:
      - piaca-net
    labels:
      - traefik.enable=true
      - traefik.http.routers.godparenthood.rule=PathPrefix(`/godparenthood`)
      - traefik.http.routers.godparenthood.entrypoints=web
      - traefik.http.services.godparenthood.loadbalancer.server.port=3004


networks:
  piaca-net:
    driver: bridge